#!/usr/bin/env sh

echo "-----------git提交信息校验-----------"
echo "ⓘ   提交规范: 遵循Conventional Commits规范。"
echo "ⓘ   规范详情: https://github.com/YuluoY/ucc-blog-back/blob/main/commitlint.config.js"
npx --no -- commitlint --edit ${1}
